name: flutter_feature_generator
description: A powerful code generator with web interface for creating clean architecture features in Flutter projects from OpenAPI/Swagger specifications.
version: 2.0.0
repository: https://github.com/MohamadsFakih/flutter_feature_generator
homepage: https://pub.dev/packages/flutter_feature_generator
documentation: https://github.com/MohamadsFakih/flutter_feature_generator/blob/master/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  flutter_feature_generator:

# Remove this line to publish to pub.dev instead of onepub.dev
# publish_to: https://onepub.dev/api/xbpdsdavuh/
